spring.application.name=febe
spring.main.banner-mode=off


# JDBC Properties
spring.datasource.url=jdbc:mysql://localhost:3306/febe_project
spring.datasource.username=root
spring.datasource.password=6#44e63#GkxPtXvdC^iY%gJU8^G6b3Gy

# The schema is managed by the scripts in src/sql-scripts
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Log Hibernate SQL Statements
logging.level.root=warn
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace
